export interface RecoveryMovementContent {
  slug: string;
  name: string;
  movementPattern: string;
  targetAreas: string[];
  setup: string;
  execution: string;
  cues: string[];
  mistakes: string[];
  stopGuidance: string;
  imagePath: string;
  imageAlt: string;
}

export const RECOVERY_MOVEMENTS: RecoveryMovementContent[] = [
  {
    slug: "childs_pose_breathing", name: "Breathing + Child’s Pose", movementPattern: "recovery breathing",
    targetAreas: ["back", "hips", "shoulders", "breathing"],
    setup: "Kneel on a mat with your big toes near each other and knees at a comfortable width. Place padding under your knees if needed.",
    execution: "Sit your hips gently toward your heels, fold your torso forward, and reach your arms ahead or rest them by your sides. Take slow, relaxed breaths without forcing your hips lower.",
    cues: ["Let the mat support you.", "Breathe into your ribs and back.", "Keep the range comfortable."],
    mistakes: ["Forcing the hips to the heels.", "Holding the breath.", "Ignoring knee or ankle pressure."],
    stopGuidance: "Come out of the pose if knee, ankle, hip, or back discomfort increases. Use more padding or switch to relaxed breathing on your back.",
    imagePath: "/exercises/yoga/childs-pose.png", imageAlt: "Man demonstrating Child’s Pose on a yoga mat",
  },
  {
    slug: "cat_cow_thoracic_rotation", name: "Cat–Cow + Thoracic Rotation", movementPattern: "spinal mobility",
    targetAreas: ["spine", "upper back", "shoulders", "trunk"],
    setup: "Start on hands and knees with hands under shoulders and knees under hips. Keep your neck long and use knee padding if helpful.",
    execution: "Alternate gently between rounding and extending your spine with your breath. Then place one hand behind your head and rotate that elbow toward the ceiling while keeping your hips mostly still; repeat on both sides.",
    cues: ["Move one vertebra at a time.", "Rotate from the upper back.", "Keep the hips quiet."],
    mistakes: ["Forcing the low back into a deep arch.", "Shrugging into the shoulders.", "Twisting the hips instead of the upper back."],
    stopGuidance: "Reduce the range or stop if you feel sharp back, neck, wrist, or knee discomfort.",
    imagePath: "/exercises/yoga/cat-cow-thoracic-rotation.png", imageAlt: "Two-position demonstration of Cow Pose and kneeling thoracic rotation",
  },
  {
    slug: "gentle_low_lunge_flow", name: "Gentle Low-Lunge Flow", movementPattern: "hip mobility",
    targetAreas: ["hip flexors", "glutes", "quadriceps", "ankles"],
    setup: "From hands and knees, step one foot forward between your hands and lower the opposite knee onto a folded towel or cushion.",
    execution: "Bring your torso upright and rest your hands lightly on the front thigh. Gently shift forward until you feel a mild stretch at the front of the back hip, return, and repeat slowly before switching sides.",
    cues: ["Front knee stays near the ankle.", "Squeeze the back glute gently.", "Keep ribs stacked over hips."],
    mistakes: ["Using a stance that is too long.", "Arching the low back.", "Driving the front knee inward."],
    stopGuidance: "Shorten the stance, add knee padding, or stop if knee, hip, or back discomfort increases.",
    imagePath: "/exercises/yoga/low-lunge.png", imageAlt: "Man demonstrating a supported low lunge with padding under the back knee",
  },
  {
    slug: "down_dog_calf_pedal", name: "Down Dog to Calf Pedal", movementPattern: "whole-body mobility",
    targetAreas: ["calves", "hamstrings", "shoulders", "upper back"],
    setup: "Start on hands and knees, spread your fingers, tuck your toes, and lift your hips up and back. Keep both knees bent enough to lengthen your spine.",
    execution: "Press the floor away and alternate bending one knee while gently lengthening the opposite heel toward the floor. Move slowly rather than trying to plant either heel.",
    cues: ["Hips move up and back.", "Keep knees soft.", "Pedal the heels gently."],
    mistakes: ["Forcing the heels flat.", "Rounding the back to straighten the legs.", "Collapsing into the shoulders or wrists."],
    stopGuidance: "Return to hands and knees or stop if wrist, shoulder, back, or knee discomfort increases.",
    imagePath: "/exercises/yoga/down-dog-calf-pedal.png", imageAlt: "Two-position demonstration of Downward Dog with alternating calf pedal",
  },
  {
    slug: "supine_figure_four", name: "Supine Figure-Four Stretch", movementPattern: "hip mobility",
    targetAreas: ["glutes", "outer hips", "deep hip rotators"],
    setup: "Lie on your back with both knees bent. Cross one ankle over the opposite thigh just above the knee and keep the crossed foot gently flexed.",
    execution: "Stay here if the stretch is enough, or hold behind the uncrossed thigh and draw it toward you until you feel a mild stretch in the crossed-side hip. Repeat on both sides.",
    cues: ["Keep your head and shoulders relaxed.", "Hold behind the thigh, not the knee.", "Use a mild, steady stretch."],
    mistakes: ["Pressing directly on the crossed knee.", "Pulling so hard that the hips curl off the floor.", "Holding the breath."],
    stopGuidance: "Release the stretch if it creates knee, hip, or back pain; keep the uncrossed foot on the floor for a gentler option.",
    imagePath: "/exercises/yoga/supine-figure-four.png", imageAlt: "Man demonstrating a supine figure-four hip stretch",
  },
  {
    slug: "relaxed_diaphragmatic_breathing", name: "Relaxed Diaphragmatic Breathing", movementPattern: "recovery breathing",
    targetAreas: ["breathing", "rib cage", "trunk", "relaxation"],
    setup: "Lie on your back with knees bent and feet supported, or sit comfortably. Place one hand on your chest and the other on your abdomen.",
    execution: "Breathe in slowly through your nose and let the lower hand rise gently. Exhale without forcing it, allowing your jaw, neck, and shoulders to soften.",
    cues: ["Quiet breath in through the nose.", "Let the lower ribs expand.", "Make the exhale easy and unforced."],
    mistakes: ["Taking very large forced breaths.", "Lifting or tensing the shoulders.", "Treating the breathing as a performance test."],
    stopGuidance: "Return to normal breathing if you feel lightheaded, anxious, or uncomfortable.",
    imagePath: "/exercises/yoga/relaxed-breathing.png", imageAlt: "Man lying comfortably with one hand on his chest and one on his abdomen for relaxed breathing",
  },
  {
    slug: "easy_breathing", name: "Easy Breathing", movementPattern: "recovery breathing",
    targetAreas: ["breathing", "rib cage", "neck", "relaxation"],
    setup: "Lie on your back with knees bent or sit in a supported position. Let your hands rest comfortably and soften your jaw and shoulders.",
    execution: "Breathe quietly through your nose at a natural pace. Let the lower ribs and abdomen move without trying to take the biggest possible breath.",
    cues: ["Keep the breath quiet.", "Relax your jaw and shoulders.", "Let the exhale happen without force."],
    mistakes: ["Forcing very deep breaths.", "Lifting the shoulders with every inhale.", "Holding the breath between cycles."],
    stopGuidance: "Return to normal breathing or sit up if you feel lightheaded, anxious, or uncomfortable.",
    imagePath: "/exercises/yoga/relaxed-breathing.png", imageAlt: "Man lying comfortably for easy relaxed breathing",
  },
  {
    slug: "gentle_cat_cow", name: "Gentle Cat–Cow", movementPattern: "spinal mobility",
    targetAreas: ["spine", "upper back", "trunk", "shoulders"],
    setup: "Start on hands and knees with hands under shoulders, knees under hips, and your neck in line with your spine. Add knee padding if helpful.",
    execution: "Exhale as you gently round your spine and let your head follow. Inhale as you tip the pelvis, open the chest, and return through a comfortable extension. Continue slowly.",
    cues: ["Move with your breath.", "Use the whole spine gently.", "Keep shoulders away from ears."],
    mistakes: ["Forcing a deep low-back arch.", "Moving quickly between positions.", "Locking the elbows or shrugging."],
    stopGuidance: "Reduce the range or stop if wrist, knee, neck, or back discomfort increases.",
    imagePath: "/exercises/yoga/cat-cow-thoracic-rotation.png", imageAlt: "Man demonstrating the extended position of a gentle Cat–Cow movement",
  },
  {
    slug: "standing_ankle_rocks", name: "Standing Ankle Rocks", movementPattern: "ankle mobility",
    targetAreas: ["ankles", "calves", "soleus"],
    setup: "Face a wall in a short staggered stance with the working foot forward and flat. Touch the wall lightly for balance.",
    execution: "Glide the front knee toward the wall over the middle toes while keeping the heel planted, then return. Repeat gently before switching sides.",
    cues: ["Keep the whole heel down.", "Knee tracks over middle toes.", "Use a smooth forward glide."],
    mistakes: ["Letting the heel lift.", "Collapsing the arch or knee inward.", "Forcing the knee farther than comfortable."],
    stopGuidance: "Shorten the range or stop if ankle, foot, or knee discomfort increases.",
    imagePath: "/exercises/yoga/ankle-rocks.png", imageAlt: "Man demonstrating a wall-supported standing ankle rock",
  },
  {
    slug: "ninety_ninety_hip_switches", name: "90/90 Hip Switches", movementPattern: "hip mobility",
    targetAreas: ["hips", "glutes", "deep hip rotators"],
    setup: "Sit with both knees bent and feet wider than your hips. Place your hands behind you for support and keep your torso tall.",
    execution: "Lower both knees together toward one side, return through center, and rotate them toward the other side. Move only through a comfortable range.",
    cues: ["Keep both sitting bones heavy.", "Move the knees together.", "Use your hands for support."],
    mistakes: ["Forcing either knee to the floor.", "Collapsing through the low back.", "Moving so quickly that control is lost."],
    stopGuidance: "Use a smaller range or stop if hip, groin, or knee discomfort increases.",
    imagePath: "/exercises/yoga/90-90-hip-switches.png", imageAlt: "Two-position demonstration of seated 90/90 hip switches",
  },
  {
    slug: "half_kneeling_hip_flexor_stretch", name: "Half-Kneeling Hip-Flexor Stretch", movementPattern: "hip mobility",
    targetAreas: ["hip flexors", "quadriceps", "glutes"],
    setup: "Kneel on a folded towel with the opposite foot forward. Keep the front knee near the ankle and place your hands on your hips.",
    execution: "Gently tuck the pelvis and squeeze the glute of the kneeling side. Shift forward slightly until you feel a mild stretch at the front of that hip.",
    cues: ["Squeeze the back-side glute.", "Keep ribs stacked over hips.", "Use a small forward shift."],
    mistakes: ["Arching the low back.", "Using an overly long stance.", "Driving into pressure at the kneeling knee."],
    stopGuidance: "Add padding, shorten the stance, or stop if knee, hip, or back discomfort increases.",
    imagePath: "/exercises/yoga/half-kneeling-hip-flexor-stretch.png", imageAlt: "Man demonstrating a padded half-kneeling hip-flexor stretch",
  },
  {
    slug: "wall_calf_stretch", name: "Wall Calf Stretch", movementPattern: "calf mobility",
    targetAreas: ["calves", "ankles", "Achilles area"],
    setup: "Face a wall in a staggered stance with both feet pointing forward. Place your hands on the wall and keep the back heel down.",
    execution: "Bend the front knee and lean forward gently while keeping the back leg straight and heel planted. Hold a mild stretch, then switch sides.",
    cues: ["Back heel stays grounded.", "Back knee stays straight but not locked.", "Both feet point forward."],
    mistakes: ["Turning the back foot outward.", "Letting the back heel lift.", "Leaning so far that the stretch becomes painful."],
    stopGuidance: "Ease out or stop if calf, Achilles, ankle, or knee discomfort increases.",
    imagePath: "/exercises/yoga/calf-stretch.png", imageAlt: "Man demonstrating a wall-supported straight-knee calf stretch",
  },
  {
    slug: "easy_walk_in_place", name: "Easy Walk in Place", movementPattern: "gentle movement",
    targetAreas: ["hips", "knees", "ankles", "whole body"],
    setup: "Stand tall near a wall or chair if you want support. Let your arms hang naturally and keep your feet under your hips.",
    execution: "Walk gently in place with small comfortable steps and an easy arm swing. Keep the effort low enough to breathe and talk normally.",
    cues: ["Use small easy steps.", "Stay tall and relaxed.", "Let the arms swing naturally."],
    mistakes: ["Turning it into high-knee marching.", "Holding the breath or tensing shoulders.", "Moving faster than a recovery effort."],
    stopGuidance: "Slow down, use support, or stop if balance, knee, hip, or ankle discomfort increases.",
    imagePath: "/exercises/yoga/easy-walk-in-place.png", imageAlt: "Man demonstrating a relaxed walk in place",
  },
  {
    slug: "adductor_rock_back", name: "Adductor Rock-Back", movementPattern: "hip mobility",
    targetAreas: ["adductors", "inner thighs", "hips"],
    setup: "Start on hands and knees. Extend one leg straight to the side with the foot supported, and add padding under the kneeling knee.",
    execution: "Keep your spine long as you shift your hips gently backward until you feel a mild inner-thigh stretch, then return forward. Repeat before switching sides.",
    cues: ["Keep the side leg long.", "Send hips back, not sideways.", "Maintain a long spine."],
    mistakes: ["Rounding the back.", "Turning it into a deep side lunge.", "Forcing a wide leg position."],
    stopGuidance: "Narrow the position or stop if groin, hip, knee, or back discomfort increases.",
    imagePath: "/exercises/yoga/adductor-rock-back.png", imageAlt: "Two-position demonstration of a kneeling adductor rock-back",
  },
  {
    slug: "bent_knee_calf_stretch", name: "Bent-Knee Calf Stretch", movementPattern: "calf mobility",
    targetAreas: ["soleus", "lower calf", "ankles", "Achilles area"],
    setup: "Face a wall in a short staggered stance with both feet forward and the back heel planted. Use the wall for support.",
    execution: "Bend both knees slightly and let the back knee move forward while keeping its heel down. Hold a mild lower-calf stretch, then switch sides.",
    cues: ["Bend the back knee.", "Keep the back heel heavy.", "Use a short comfortable stance."],
    mistakes: ["Straightening the back knee.", "Letting the heel lift.", "Dropping into a deep squat."],
    stopGuidance: "Reduce the bend or stop if Achilles, calf, ankle, or knee discomfort increases.",
    imagePath: "/exercises/yoga/bent-knee-calf-stretch.png", imageAlt: "Man demonstrating a wall-supported bent-knee calf stretch",
  },
  {
    slug: "open_book_rotation", name: "Open-Book Rotation", movementPattern: "spinal mobility",
    targetAreas: ["upper back", "chest", "shoulders", "trunk"],
    setup: "Lie on one side with hips and knees bent and stacked. Extend both arms in front of your chest with palms together.",
    execution: "Sweep the top arm open across your body while your eyes follow the hand. Keep the knees together and rotate only as far as comfortable, then return and repeat on both sides.",
    cues: ["Keep the knees stacked.", "Follow the hand with your eyes.", "Rotate through the upper back."],
    mistakes: ["Letting the top knee roll backward.", "Forcing the hand to the floor.", "Shrugging the moving shoulder."],
    stopGuidance: "Use a smaller range or stop if shoulder, neck, back, hip, or knee discomfort increases.",
    imagePath: "/exercises/yoga/open-book-rotation.png", imageAlt: "Man demonstrating the open position of an open-book rotation",
  },
  {
    slug: "gentle_wall_slides", name: "Gentle Wall Slides", movementPattern: "shoulder mobility",
    targetAreas: ["shoulders", "upper back", "chest"],
    setup: "Stand with your back against a wall, feet slightly forward, and ribs relaxed. Place your elbows and forearms against or near the wall in a comfortable goalpost shape.",
    execution: "Slide your arms upward only as far as you can without shrugging or arching your back, then return slowly to the start.",
    cues: ["Keep ribs relaxed.", "Slide without shrugging.", "Use only a comfortable range."],
    mistakes: ["Arching the low back.", "Forcing wrists or elbows against the wall.", "Raising the arms through shoulder pain."],
    stopGuidance: "Reduce the range or stop if shoulder, neck, or back discomfort increases.",
    imagePath: "/exercises/yoga/wall-slides.png", imageAlt: "Two-position demonstration of gentle wall slides",
  },
  {
    slug: "childs_pose_side_reach", name: "Child’s Pose Side Reach", movementPattern: "whole-body mobility",
    targetAreas: ["upper back", "lats", "shoulders", "hips"],
    setup: "Settle into a comfortable Child’s Pose with knees supported as needed and arms reaching forward.",
    execution: "Walk both hands diagonally to one side until you feel a mild stretch along the opposite side of your torso. Return to center and repeat on the other side.",
    cues: ["Keep hips gently toward heels.", "Reach both hands together.", "Breathe into the stretched side."],
    mistakes: ["Forcing the hips down.", "Twisting instead of reaching sideways.", "Ignoring knee or shoulder pressure."],
    stopGuidance: "Use more padding, reduce the reach, or stop if knee, hip, shoulder, or back discomfort increases.",
    imagePath: "/exercises/yoga/childs-pose-reach.png", imageAlt: "Two-position demonstration of Child’s Pose side reaches",
  },
];

export function getRecoveryMovement(slug: string | null | undefined) {
  return RECOVERY_MOVEMENTS.find((movement) => movement.slug === slug) ?? null;
}
